### ISSUE TITLE
Unicode Issue

### ISSUE THREAD

**Issue by alexrashed** [alexrashed/docker-urlwatch2#2]
When the detail print on the console is activated and the text contains some unicode characters, urlwatch crashes (and no notifications are sent):
```
--- @	Thu, 04 May 2017 21:45:06 +0000
+++ @	Fri, 05 May 2017 07:30:07 +0000
@@ -28,6 +28,12 @@
 -
 Exams
 Midterm
+Midterm Exam
+-
+25,00
Traceback (most recent call last):
  File "/usr/local/bin/urlwatch", line 101, in <module>
    urlwatch_command.run()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/command.py", line 167, in run
    self.urlwatcher.close()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/main.py", line 96, in close
    self.report.finish()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/handler.py", line 125, in finish
    ReporterBase.submit_all(self, self.job_states, duration)
  File "/usr/local/lib/python3.6/site-packages/urlwatch/reporters.py", line 92, in submit_all
    subclass(report, cfg, job_states, duration).submit()
  File "/usr/local/lib/python3.6/site-packages/urlwatch/reporters.py", line 313, in submit
    print(self._green(line))
UnicodeEncodeError: 'ascii' codec can't encode character '\u2013' in position 2: ordinal not in range(128)
```

**Comment by alexrashed** [comment]
Seems to be addressed in this issues:
- https://github.com/thp/urlwatch/issues/44
- https://github.com/thp/urlwatch/issues/48

**Comment by alexrashed** [comment]
Wixed with 591a4439662fb97d02579653048789c4c5744f26
